WIP stop failing to register devices with bouncer; TODO debug errors
Before this change, the dev server spews a lengthy internal error
any time the mobile app connects to it.  Like this:

2023-12-26 20:39:37.152 INFO [zr] 127.0.0.1       POST    200 166ms (db: 55ms/39q) /api/v1/register (8@zulip via Dart)
2023-12-26 20:39:37.374 INFO [zerver.lib.push_notifications] Registering push device: […]
2023-12-26 20:39:37.382 INFO [zerver.lib.push_notifications] Sending new push device to bouncer: […]
2023-12-26 20:39:37.391 ERR  [django.request] Bad Gateway: /api/v1/users/me/android_gcm_reg_id
Traceback (most recent call last):
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f5ebb3aa220>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='push.192.168.0.113', port=9991): Max retries exceeded with url: /api/v1/remotes/push/register (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5ebb3aa220>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/zulip/zerver/lib/remote_server.py", line 154, in send_to_push_bouncer
    res = session.request(
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/srv/zulip/zerver/lib/outgoing_http.py", line 43, in send
    return super().send(*args, **kwargs)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='push.192.168.0.113', port=9991): Max retries exceeded with url: /api/v1/remotes/push/register (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5ebb3aa220>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/zulip/zerver/middleware.py", line 402, in process_exception
    raise exception  # Ensure correct sys.exc_info().
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/zulip/zerver/lib/rest.py", line 39, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/srv/zulip/zerver/lib/rest.py", line 203, in rest_dispatch
    return target_function(request, **kwargs)
  File "/srv/zulip-py3-venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/srv/zulip/zerver/decorator.py", line 779, in _wrapped_func_arguments
    raise err
  File "/srv/zulip/zerver/decorator.py", line 776, in _wrapped_func_arguments
    return view_func(request, user_profile, *args, **kwargs)
  File "/srv/zulip/zerver/decorator.py", line 516, in _wrapped_view_func
    return view_func(request, *args, **kwargs)
  File "/srv/zulip/zerver/lib/request.py", line 464, in _wrapped_req_func
    return_value = req_func(request, *args, **kwargs)
  File "/srv/zulip/zerver/views/push_notifications.py", line 76, in add_android_reg_id
    add_push_device_token(user_profile, token, PushDeviceToken.GCM)
  File "/srv/zulip/zerver/lib/push_notifications.py", line 723, in add_push_device_token
    send_to_push_bouncer("POST", "push/register", post_data)
  File "/srv/zulip/zerver/lib/remote_server.py", line 167, in send_to_push_bouncer
    raise PushNotificationBouncerRetryLaterError(
zerver.lib.remote_server.PushNotificationBouncerRetryLaterError: ConnectionError while trying to connect to push notification bouncer
2023-12-26 20:39:37.396 INFO [zr] 127.0.0.1       POST    502  23ms (db: 1ms/1q) /api/v1/users/me/android_gcm_reg_id (8@zulip via Dart)
2023-12-26 20:39:37.396 ERR  [django.server] "POST /api/v1/users/me/android_gcm_reg_id HTTP/1.1" 502 117